version: "3.0"

services:

  apis:
    build: ./
    restart: on-failure:5
    environment:
      - DB_HOST=postgres://postgres:rahasiailahi@database:5432/postgres?sslmode=disable
      - REDIS_HOST=localhost:6379
    ports:
      - 3000:3000
    depends_on:
      - database
      - cache

  database:
    image: "postgres:12.9-alpine"
    restart: on-failure:3
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rahasiailahi
      - POSTGRES_DB=postgres

  
  cache:
    image: "redis:alpine"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes